trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  displayName: 'Checkout Repository'

- script: |
    echo "Listing current directory structure:"
    ls -la
    pwd
  displayName: 'List Files in Directory'

- task: NodeTool@0
  inputs:
    versionSpec: '18.x' # Use a stable Node.js version
  displayName: 'Install Node.js'

- script: |
    echo "Installing dependencies..."
    npm install
    npm run build
  workingDirectory: $(System.DefaultWorkingDirectory)/src # Adjust if package.json is in a subfolder
  displayName: 'Install Dependencies and Build'
