trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  displayName: 'Checkout Repository'

- script: |
    echo "Listing current directory structure:"
    ls -la
    pwd
  displayName: 'List Files and Current Directory'

- task: NodeTool@0
  inputs:
    versionSpec: '18.x' # Use a stable Node.js version
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  workingDirectory: $(System.DefaultWorkingDirectory) # Update based on directory structure
  displayName: 'Install Dependencies and Build'
